version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db-news-app
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U news_admin -d news_app_prod']
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - app-network

  news_app:
    container_name: news-app-news_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-5000}:5000' # Use PORT from .env, default to 5000 if not set
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod
    volumes:
      - ./src:/usr/src/app/src # Sync local src folder to container
      - ./node_modules:/usr/src/app/node_modules # Set up shared dependencies
    command: npx nodemon --watch src --exec node --loader ts-node/esm -r dotenv/config src/index.ts
    networks:
      - app-network

networks:
  app-network:
    name: app-network # Define shared network
